### ISSUE TITLE
When adding a participant to a study it always says "First to run" initially (even when it's actually queued)

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#67]
Take a participant who is already participating in study A with priority 1. Then add this participant to study B with priority 1. Initially, the participant will be listed as 'First to run' under B. Only when the page is reloaded, this is changed to 'Queued at position 1'.

**Comment by dschreij** [comment]
Yep, I noticed that too. Will look into that during my next session of fixes.

**Comment by dschreij** [comment]
Hmm, locally this doesn't happen for me. So either I already fixed it (I remember something as such), or there is a difference between remote and local that causes this discrepancy. In any case, further investigations are required.

**Comment by dschreij** [comment]
I see that I incorrectly attributed a commit to this issue, while it should have been attributed to https://github.com/open-cogsci/omm-server/issues/63

**Comment by smathot** [comment]
I still see this locally with the latest snapshot from `development`.

**Comment by dschreij** [comment]
Alright. I will have to make some other attempts at reproducing this then!

**Comment by smathot** [comment]
The way I reproduce it is by first creating the match-to-sample experiment (from the client source) and assigning a participant to it. Then creating the lexical-decision experiment and assigning the same participant to it. Initially, this will show that the lexical-decision experiment is the first to run (incorrect), but after navigating to another page and returning it says that the experiment is queued (correct).

**Comment by dschreij** [comment]
I can reproduce it now too. If I add the same participant to various experiment multiple times, the queue position in not always first to run, but it seems as if each time the queue position is one lower than it should be. After a refresh, the queue position is correct.

**Comment by dschreij** [comment]
Should be fixed and on the development branch now. This was a very stupid mistake where the queue positions were not refreshed after changing participants' assignments. Luckily this also made it easy to solve.

**Comment by smathot** [comment]
Just tested it, and it's indeed fixed!
